### ISSUE TITLE
Recommend systemd-timesyncd over ntp on Debian / Ubuntu

### ISSUE THREAD

**Issue by maccadia** [tranquilit/WAPT#31]
[The documentation for WAPT 2.2](https://www.wapt.fr/fr/doc-2.2/wapt-server-install-debian-based.html#configuring-the-ip-address-of-the-wapt-server) recommends installing the `ntp` package on Debian / Ubuntu.

Debian 11 and Ubuntu 20.04 both come with `systemd-timesyncd` preinstalled and don't require the `ntp` package for time synchronization.

**Comment by d-cardon** [comment]
thanks for the input, it has been fixed on the internal git tree and should be updated on the public doc in the next few days
