### ISSUE TITLE
Ability to specify the db_port

### ISSUE THREAD

**Issue by geodb27** [tranquilit/WAPT#4]
Hello !
I've freshly installed last wapt server on a debian 9 "machine". It works fine. However, I must separate the database from this "machine". So, I went through the documentation and saw these parameters : 
https://www.wapt.fr/fr/doc/Configuration/ini_file/index.html
db_name=wapt
db_host=where.i.want.my.database.server
db_user=wapt
db_password=mysecretpassword

Could it be possible to add a parameter (unless I did not understand the docs clearly), named after db_port for example ?
On my network, the postgres server that will host the wapt database don't listen on 5432 port...

**Comment by htouvet** [comment]
will be in release 1.6.2.2.
