### ISSUE TITLE
Erreur dans la fonction installed_softwares du setuphelper.py

### ISSUE THREAD

**Issue by ochabert** [tranquilit/WAPT#7]
Bonjour,

en voulant utiliser la possibilité de faire une recherche de logiciel installé (fonction installed_softwares) avec le paramètre name et une expression régulière, je suis tomber sur un problème de fonctionnement.

lorsque l'on fait l'appel à la fonction comme ceci:
```
 softs = installed_softwares(name='Regex_ToFind')
 if softs:
      for soft in softs:
           print soft["name"]
```
la fonction retourne tout les logiciels présent, au lieu des logiciels dont le diplay_name commence par la l'expression régulière que l'on recherche.

il doit donc y avoir une erreur dans le test ligne 2330 
```
 if (uninstallkey is None and display_name and check_words(subkey+' '+display_name+' '+publisher,mykeywords)) or\
             (uninstallkey is not None and (subkey == uninstallkey)) or\
             (name_re is not None and name_re.match(display_name)):
```
à remplacer par :
```
 if (uninstallkey is None and name_re is None and display_name and check_words(subkey+' '+display_name+' '+publisher,mykeywords)) or\
             (uninstallkey is not None and (subkey == uninstallkey)) or\
             (name_re is not None and name_re.match(display_name)):

```

cordialement

**Comment by htouvet** [comment]
Merci pour cette contribution.
https://github.com/tranquilit/WAPT/commit/acb39661b809deabce504dce16dae94896e5964e
