### ISSUE TITLE
wapt not get windows 7 env

### ISSUE THREAD

**Issue by empereira** [tranquilit/WAPT#8]
Hello,

Configs:
WAPT Server version: 1.7.3.5
WAPT Agent version: 1.7.3.5
WAPT Setup version: 1.7.3.5
WAPT Deploy version: 1.7.3.5
DB status: OK (1.7.3.2)

wapt not get "HOMEDRIVE" env from windows 7. It's returns:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\wapt\common.py", line 3619, in install_wapt
    setup = import_setup(setup_filename)
  File "C:\Program Files (x86)\wapt\waptutils.py", line 1252, in import_setup
    py_mod = imp.load_source(modulename, setupfilename.encode(sys.getfilesystemencoding()))
  File "c:\windows\temp\waptswfot1\setup.py", line 11, in <module>
  File "C:\Program Files (x86)\wapt\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'HOMEDRIVE'
KeyError: 'HOMEDRIVE'
```

Code for test:
```
# -*- coding: utf-8 -*-

from setuphelpers import *
import os

uninstallkey=[]

env = os.environ['HOMEDRIVE']
print env
```

windows 7 client env:
image attached
![Captura de tela_2019-04-15_10-38-37](https://user-images.githubusercontent.com/29874574/56137565-83ddc780-5f6b-11e9-83aa-0b458ee66470.png)

**Comment by htouvet** [comment]
HOMEDRIVE variable is not set for system account's environment.
And waptservice is running as system account...
